# Generated by Django 4.2.11 on 2024-03-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="challenge",
            field=models.FloatField(default=0.4),
        ),
    ]
